### ISSUE TITLE
Vim not respecting cterm colors for markbar items

### ISSUE THREAD

**Issue by xoihiox** [Yilin-Yang/vim-markbar#16]
I am a bit lost here.  For some reason, none of the default syntax highlighting worked out of the box.  When I define the colors myself, I seem to only be able to update the colors for `markbarContext` and `markbarContextMarkHighlight`.

I have this pasted at the bottom of my .vimrc while I try and figure this thing out:

```
filetype plugin indent on                                                                
set t_Co=256                                                                             
syntax enable                                                                            
set autoread                                                                             
set hidden                                                                               
hi markbarContext ctermfg=green                                                          
hi markbarContextMarkHighlight cterm=bold ctermfg=magenta                                
hi markbarSectionLowercaseMark cterm=bold ctermfg=red                                    
hi markbarSectionSpecialLocalMark cterm=bold ctermbg=57 ctermbg=57                       
hi markbarSectionName cterm=underline ctermfg=green ctermbg=green                        
hi markbarSectionNumberedMark cterm=bold ctermfg=yellow ctermbg=yellow 
```
Other than this, I have no issues with colorscheme rendering in vim.  I am currently running a variation of badwolf, and markbar syntax does change with my colorscheme, but displays the default color for all items.

Any ideas?  Thanks.

**Comment by xoihiox** [comment]
I found the culprit:

[Plugin 'luochen1990/rainbow' ](https://github.com/luochen1990/rainbow)

Do you know how I might selectively disable that plugin for the markbar window only?

Thanks.

**Comment by Yilin-Yang** [comment]
Hi xoihiox,

vim-markbar sets a `b:is_markbar` variable inside of the markbar. My first thought is that you could `let g:rainbow_active = 0` in your vimrc, `RainbowToggle" to turn the plugin on "globally", and set up an `autocmd BufEnter` that toggles the plugin back off if `exists('b:is_markbar')` returns true, and which turns it back on if that function returns false.

It also looks like rainbow lets you configure it on a per-filetype basis; the markbar window has filetype `markbar`, which you might be able to use to turn the plugin off in the markbar window.

I'm afraid that I can't offer too much help for this, unfortunately, since this looks like an issue localized to another plugin not under my direct control.

-Yilin
