### ISSUE TITLE
Persist mark names, show line/col no. when renaming marks, and better position cursor on open

### ISSUE THREAD

**Issue by xoihiox** [Yilin-Yang/vim-markbar#17]
Okay, say for mark under mark 'a' the markbar is showing this entry: `['a]: Plugin Config`.  
  A couple of things:

1. While mark a persists across sessions, the user-added title of `Plugin Config` is wiped whenever I close the file.  Can you tell me how to fix this?
2. The user-added title wipes out the line and column information that exists for unnamed marks.  It would be nice to at least retain the line number.
3.  Whenever I open my markbar, the cursor is always on the final entry.  I can press `gg` to get the the top, but the default opening position is always `G`.  Is this normal behavior?

Thanks.

**Comment by Yilin-Yang** [comment]
Hi, xoihiox,

1. Persistent mark names would require writing the user's mark names to an output file, which is something I wanted to implement, but didn't get around to doing. The current behavior isn't a bug, it's just a TODO/"not implemented yet."
2. Agreed; I can add that to the TODO.
3. That's normal behavior when running vim-markbar in vim, rather than neovim. vim-markbar has a "set lines in buffer" function that uses different implementations in vim vs. neovim, and the implementation for the former pushes the cursor to the bottom of the buffer as a side effect. The relevant code is [here](https://github.com/Yilin-Yang/vim-markbar/blob/d7492e3236d4dbadae60e44d7f87ccc952b2c6ba/autoload/markbar/helpers.vim#L226).  A better fix would make use of the (better) "set lines in buffer" helpers I wrote for my TypeVim plugin, but that adds two more plugin dependencies (vim-maktaba + TypeVim itself); you can try pulling from the `typevim` branch ([ref](https://github.com/Yilin-Yang/vim-markbar/issues/15#issuecomment-515649384)) to see if that fixes the issue.

This is something that I'd like to work on, but I've been pretty busy with coursework lately, so I can't promise to fix things quickly. I do (genuinely) appreciate the feedback, though; vim-markbar has been languishing in my back catalog for a little while.

-Yilin
