### ISSUE TITLE
Feature request: map 'q' to close markbar

### ISSUE THREAD

**Issue by tzws** [Yilin-Yang/vim-markbar#28]
I disabled peekaboo. But sometimes, I want to peek the marks, and just close markbar by 'q'

**Comment by Yilin-Yang** [comment]
Hi, sorry for the delay. I forgot to include this in the peekaboo help text, but you can close the peekaboo markbar without jumping to a mark by pressing `Esc`. Is that the behavior you want, or do you want to be able to set your own mapping (so that you can close the peekaboo markbar with `q` rather than `Esc`)?
