### ISSUE TITLE
vim-markbar is too slow for regular use

### ISSUE THREAD

**Issue by andrewferrier** [Yilin-Yang/vim-markbar#6]
vim-markbar seems like a great idea (I regularly use vim-peekaboo, so understand the concept). However, there seems to be a delay of approx 500ms after hitting `'`, which makes it fairly impractical in daily usage. If you *don't* know which mark you want, that's OK - but if you do, hitting `'a` (for example, to go to mark *a*) introduces a 500ms delay. I was expecting/hoping it would be instant, but the markbar is still opened after the delay, then immediately closed. 

Perhaps I've missed a configuration option? It seems like strange behaviour. I was hoping for behaviour a bit like https://github.com/liuchengxu/vim-which-key, which shows the prompt window only if there is a delay after the first key is hit. vim-peekaboo doesn't have the issue either, because the peekaboo window is near instant.

Thanks - and hope this comes across as constructive! I think vim-markbar is a great idea and I wish it worked for me.

**Comment by andrewferrier** [comment]
If it's relevant, I'm using it on NVIM v0.3.1.

**Comment by Yilin-Yang** [comment]
Hey Andrew,

Don't worry, you didn't miss a configuration option. I also experience the slowdown that you describe when I use vim in WSL, and the improved behavior that you describe is just something that had slipped off my roadmap

I've pushed some changes to the `issue_6` branch that only opens the peekaboo markbar if you tap `'` or `` ` `` and then wait (so that `'a` should now just jump straight to mark `a` without trying to open the markbar for no reason). Could you pull from that branch and let know if it works for you?

Best,
Yilin

**Comment by Yilin-Yang** [comment]
Actually, I think I _might've_ been able to fix the slowdown directly. 

The function that I call inside vim-markbar to fetch a mark's lines of context will _first_ try to read those lines from an open buffer. If that fails, it'll try to read those lines directly from the file in which the mark was set: first, by trying to print those lines from the file through an external call to `sed`, and if that failed, by trying to read those lines with vim's built-in `readfile()` function. (This was meant to save on memory usage, since `readfile()` loads the entire target file at once).

If you're using WSL like I am (which has known issues with slow file I/O), the call to `sed` is _really_ slow. Removing it entirely dropped the markbar's time-to-open from ~0.5 sec to ~0.1 sec on my machine.

I've pushed that change to `issue_6`; let me know if that was enough to fix the issue. If not, then try to `let g:markbar_explicitly_remap_mark_mappings = v:true` to get the "short-circuit" behavior you'd mentioned for when you already know your target mark; please let me know if that works for you, as well!

**Comment by andrewferrier** [comment]
Excellent! So I've tried branch `issue_6` and that is much closer to what I expected; it's usable for me now, thanks! Opening and closing the markbar window is essentially instant, and if I don't "use" it, it just flickers on the side of the screen and disappears quickly like vim-peekaboo. I didn't need to use `g:markbar_explicitly_remap_mark_mappings`.

FWIW, I'm using nvim directly on OSX.

**Comment by Yilin-Yang** [comment]
I'm happy to hear it! I'll close the issue for the time being, but please feel free to reopen it/open a new one if additional problems come up. Thanks so much for your help!

**Comment by andrewferrier** [comment]
Cool, thanks. Do you plan to merge `issue-6` into `master`?

**Comment by andrewferrier** [comment]
Never - I see you have!
