### ISSUE TITLE
Peekaboo markbar is opening in Select mode

### ISSUE THREAD

**Issue by ColinKennedy** [Yilin-Yang/vim-markbar#7]
I've noticed while using this plug-in that the peekaboo window pops up in Vim's Select mode. IIRC you can't jump to another mark from Select mode because typing ` or ' would place you immediately into Insert mode and the characters are typed out. Because of this, I think the peekaboo window should not show from Select mode and be hidden like Insert mode. Please let me know if this can be done and if you agree.

**Comment by Yilin-Yang** [comment]
Hey, Colin!

I definitely agree with you on this; the special behavior of `Select` mode didn't occur to me when I was setting those mappings.

I'll work on this as soon as I'm able, but in the meantime, you should be able to fix this behavior by doing something like:
```vim
" random mapping that'll never trigger accidentally
let g:markbar_peekaboo_apostrophe_mapping = '-48s312'
let g:markbar_peekaboo_backtick_mapping = '-48s312'
nmap ' <Plug>OpenMarkbarPeekabooApostrophe
xmap ' <Plug>OpenMarkbarPeekabooApostrophe
nmap ` <Plug>OpenMarkbarPeekabooBacktick
xmap ` <Plug>OpenMarkbarPeekabooBacktick
```

Best,
Yilin

**Comment by ColinKennedy** [comment]
Those settings worked for me, thank you!

**Comment by Yilin-Yang** [comment]
Hey, Colin,

I've pushed some changes to the `issue_7` branch; these should hopefully act as a more permanent fix. By default, the peekaboo markbar now only opens from normal mode, and it's possible to disable the default peekaboo mappings with a setting (`g:markbar_set_default_peekaboo_mappings`) instead of the "random mapping" workaround that I mentioned above.

If you have the time, could you pull from that branch and see if it works for you?

Thanks!
Yilin

**Comment by Yilin-Yang** [comment]
Hey, Colin,

Since it sounds like the original issue's been fixed, and since the new branch doesn't make substantial changes/still passes the test suite, I've gone ahead and merged the changes into master. If the issue still persists for you, or if the new changes broke other things, please don't be afraid to reopen this issue, or to open a new one!

Best,
Yilin
